-- =====================================================================
-- L2 (gold) — Operations extension: fulfillment, operating rate,
-- equipment health, component cover and serial genealogy.
-- Source: SAP_SUPPLY_CHAIN.OPS_EXT (demo enrichment keyed to SAP master
-- data — plants, work centers, materials, BOM, suppliers). Generated by
-- tools/gen_ops_ext.py. Values are representative, not customer data.
-- =====================================================================

-- Customer order lines with root cause and late cost.
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_ORDER_FULFILLMENT
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'Order-level OTIF with late cause and cost (penalty 0.5%/day capped 5% + expedite). Demo enrichment.'
as
SELECT o.SALES_ORDER, o.ITEM, o.SOLD_TO, o.MATERIAL, o.MATERIAL_DESC, o.PLANT, p.PLANT_NAME, o.SHIPPING_POINT,
       o.ORDER_QTY, o.NET_VALUE_USD, o.REQUESTED_SHIP_DATE, o.ACTUAL_SHIP_DATE,
       o.ON_TIME, o.IN_FULL, (o.ON_TIME AND o.IN_FULL) AS OTIF, o.DELAY_DAYS,
       COALESCE(o.LATE_CAUSE, 'ON_TIME') AS LATE_CAUSE,
       CASE o.LATE_CAUSE WHEN 'EQUIPMENT' THEN 'Equipment outage' WHEN 'MATERIAL_SHORTAGE' THEN 'Component shortage'
            WHEN 'PERFORMANCE' THEN 'Rate below plan' WHEN 'QUALITY_HOLD' THEN 'Quality hold'
            WHEN 'LOGISTICS' THEN 'Logistics / carrier' ELSE 'On time' END AS LATE_CAUSE_LABEL,
       o.PENALTY_USD, o.EXPEDITE_USD, o.LATE_COST_USD, o.ORDER_STATUS, o.MARGIN_PER_UNIT_USD,
       DATE_TRUNC('month', o.REQUESTED_SHIP_DATE) AS SHIP_MONTH
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_SALES_ORDER_ITEM o
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON p.PLANT = o.PLANT;

-- Monthly loss tree per plant: nameplate = planned + equipment + material + performance + produced.
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_OPERATING_RATE
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'Operating-rate loss tree per plant and month (units). Demo enrichment.'
as
SELECT r.PLANT, r.PLANT_NAME, r.PERIOD_DATE, r.NAMEPLATE_UNITS, r.PLANNED_DOWNTIME_UNITS, r.EQUIPMENT_LOSS_UNITS,
       r.MATERIAL_SHORTAGE_UNITS, r.PERFORMANCE_LOSS_UNITS, r.PRODUCED_UNITS, r.OPERATING_RATE_PCT,
       IFF(r.EQUIPMENT_LOSS_UNITS >= r.MATERIAL_SHORTAGE_UNITS, 'Equipment', 'Components') AS BINDING_CONSTRAINT
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_OPERATING_RATE r;

-- Equipment daily health joined to work center; value at risk uses avg margin of systems built at the plant.
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_HEALTH
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'Daily tool health (vibration, temperature, 48h failure probability). Demo enrichment.'
as
SELECT e.EQUIPMENT_ID, e.EQUIPMENT_NAME, e.EQUIPMENT_TYPE, e.WORK_CENTER, w.WORK_CENTER_DESC, e.PLANT, p.PLANT_NAME,
       e.CRITICALITY, e.REPAIR_COST_PER_HR, h.READING_DATE, h.VIBRATION_MM_S, h.TEMPERATURE_C,
       h.FAILURE_PROB_48H, h.ANOMALY_FLAG
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_EQUIPMENT e
JOIN SAP_SUPPLY_CHAIN.OPS_EXT.A_EQUIPMENT_HEALTH_DAILY h ON h.EQUIPMENT_ID = e.EQUIPMENT_ID
JOIN SAP_SUPPLY_CHAIN.WORK_CENTER.A_WORK_CENTER w ON w.WORK_CENTER = e.WORK_CENTER
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON p.PLANT = e.PLANT;

create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_OUTAGE
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'Outage events with repair cost. Demo enrichment.'
as
SELECT o.OUTAGE_ID, o.EQUIPMENT_ID, e.EQUIPMENT_NAME, o.WORK_CENTER, o.PLANT, p.PLANT_NAME, o.START_DATE,
       o.EVENT_TYPE, o.DOWNTIME_HRS, o.ROOT_CAUSE, o.REPAIR_COST_USD
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_EQUIPMENT_OUTAGE o
JOIN SAP_SUPPLY_CHAIN.OPS_EXT.A_EQUIPMENT e ON e.EQUIPMENT_ID = o.EQUIPMENT_ID
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON p.PLANT = o.PLANT;

create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_COMPONENT_COVER
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'Component days of cover vs supplier lead time per plant. Demo enrichment.'
as
SELECT c.PLANT, p.PLANT_NAME, c.COMPONENT_MATERIAL, c.COMPONENT_DESC, c.SUPPLIER, s.SUPPLIER_NAME, c.ON_HAND_QTY,
       c.DAILY_USAGE, c.DAYS_OF_COVER, c.SUPPLIER_LEAD_TIME_DAYS, c.OPEN_PO_QTY, c.STATUS,
       (c.DAYS_OF_COVER < c.SUPPLIER_LEAD_TIME_DAYS) AS COVER_BELOW_LEAD_TIME
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_COMPONENT_COVER c
JOIN SAP_SUPPLY_CHAIN.PLANT.A_PLANT p ON p.PLANT = c.PLANT
LEFT JOIN (SELECT DISTINCT SUPPLIER, SUPPLIER_NAME FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_COMPONENT_LOT) s ON s.SUPPLIER = c.SUPPLIER;

-- Digital thread: serial -> component lot -> supplier inspection -> final test -> customer order.
create or replace dynamic table SAP_SUPPLY_CHAIN.ANALYTICS.DT_SERIAL_GENEALOGY
  target_lag = 'DOWNSTREAM' refresh_mode = AUTO initialize = ON_CREATE warehouse = LOAD_WH
  comment = 'System serial genealogy to component lots, suppliers and final test. Demo enrichment.'
as
SELECT g.SERIAL_NO, g.MATERIAL, g.PLANT, g.SALES_ORDER, so.SOLD_TO, g.COMPONENT_MATERIAL, l.COMPONENT_DESC, g.LOT_ID,
       l.SUPPLIER, l.SUPPLIER_NAME, l.SUPPLIER_SOURCE, l.RECEIVED_DATE, l.INSPECTION_RESULT, l.DEVIATION_NOTE,
       t.TEST_DATE, t.RESULT AS FINAL_TEST_RESULT, t.DEFECT_CODE, t.REWORK_HRS, t.SENSITIVITY_NM
FROM SAP_SUPPLY_CHAIN.OPS_EXT.A_SERIAL_GENEALOGY g
JOIN SAP_SUPPLY_CHAIN.OPS_EXT.A_COMPONENT_LOT l ON l.LOT_ID = g.LOT_ID
JOIN SAP_SUPPLY_CHAIN.OPS_EXT.A_FINAL_TEST t ON t.SERIAL_NO = g.SERIAL_NO
JOIN SAP_SUPPLY_CHAIN.OPS_EXT.A_SALES_ORDER_ITEM so ON so.SALES_ORDER = g.SALES_ORDER;

-- Serving views (APP_REF) — the interface the app and Native App read.
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_ORDER_FULFILLMENT as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_ORDER_FULFILLMENT;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_OPERATING_RATE as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_OPERATING_RATE;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_EQUIPMENT_HEALTH as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_HEALTH;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_EQUIPMENT_OUTAGE as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_EQUIPMENT_OUTAGE;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_COMPONENT_COVER as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_COMPONENT_COVER;
create or replace view SAP_SUPPLY_CHAIN.APP_REF.DT_SERIAL_GENEALOGY as select * from SAP_SUPPLY_CHAIN.ANALYTICS.DT_SERIAL_GENEALOGY;
